name: CI (PR)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  show-secrets:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: show secrets
      run: echo "${{ secrets.NPM_TOKEN }}"
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit
  integration-tests:
    uses: ./.github/workflows/integration-tests.yml
    needs: unit-tests
